" 'nocompatible' comes first: if it ever flips (e.g. `vim -u this-file`) it
" resets other options. Implied when Vim finds ~/.vimrc; a no-op in Neovim.
set nocompatible

""" Global settings

" turn on syntax highlight
syntax on

" turn on true color
set termguicolors
if !has('nvim')
  " terminal Vim only emits truecolor escapes if these are set
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

" highlight search
set hlsearch

" disable mouse reporting
set mouse=

" filetype based indentation
filetype plugin indent on
" fallback to autoindent
" which does nothing more than copy the indentation from the previous line
" when starting a new line
set autoindent

" expand tab using space characters, each tab equals to 2 spaces
set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2

" a special column at the 80 character warns lines that are too long
set colorcolumn=80

" encoding settings
set encoding=utf-8

" more natural split opening
set splitbelow
set splitright

" no swapfile: this config began life in a container where the host user was
" mapped in, so swap writes to mounted directories hit permission errors.
" Kept since 'undofile' plus git cover the recovery case.
set noswapfile

" persist command/search history, marks and registers across sessions.
" ('viminfo' is the Vim name; Neovim accepts it as an alias for 'shada'.)
"   '100  marks for the last 100 files   <50  max 50 lines per register
"   s10   skip registers above 10KB      h    don't restore hlsearch on start
set viminfo='100,<50,s10,h

" read a project-local vimrc (Vim: ./.vimrc -- nvim 0.9+: ./.nvim.lua,
" ./.nvimrc or ./.exrc, behind a trust prompt). 'secure' restricts what such
" a file may do, which is what protects Vim, where there is no trust prompt.
set exrc
set secure

" disable safe write
set backupcopy=yes

" automatically read file changes
set autoread

" do not generate files ending with ~
" set nowritebackup

" Display extra whitespace
" set list listchars=tab:,trail:·,nbsp:·

""" Improved defaults
"
" NOTE: many settings below (hidden, incsearch, wildmenu, laststatus=2,
" autoindent, encoding, autoread, hlsearch, and syntax/filetype above) are
" already Neovim defaults but are NOT Vim defaults -- do not drop them as
" redundant, they are load-bearing under Vim.

" line numbers (relative + absolute current line)
set number
set relativenumber

" smart search: case-insensitive unless uppercase is typed
set ignorecase
set smartcase
set incsearch

" allow switching buffers without saving
set hidden

" command-line completion
set wildmenu
set wildmode=longest:full,full

" keep context lines visible when scrolling
set scrolloff=8
set sidescrolloff=8

" highlight current line
set cursorline

" always show the sign column (prevents gitgutter jitter)
set signcolumn=yes

" faster gitgutter + CursorHold events (default 4000ms is too slow)
set updatetime=250

" live preview of :s/// as you type
if exists('&inccommand')
  set inccommand=split
endif

" redundant with airline
set noshowmode

" persistent undo across sessions, kept outside this repo
set undofile
if has('nvim')
  let s:undodir = expand('~/.config/nvim/undodir')
else
  let s:undodir = expand('~/.vim/undodir')
endif
if !isdirectory(s:undodir)
  call mkdir(s:undodir, 'p', 0700)
endif
let &undodir = s:undodir

" system clipboard integration.
" nvim routes the '+' register to the OS clipboard. Vim on macOS is built
" without X11, so '+' never reaches the pasteboard and 'unnamedplus' silently
" does nothing there -- '*' is the register that works.
if has('nvim')
  set clipboard=unnamedplus
elseif has('clipboard')
  set clipboard=unnamed
endif

" always show status line
set laststatus=2

" backspace over autoindent, line breaks and start-of-insert (Vim is limited
" here by default; already the Neovim default)
set backspace=indent,eol,start

" recognise terminal key codes without hanging on a bare <Esc>
set ttimeout
set ttimeoutlen=100

""" Package manager settings

" vim-polyglot provides syntax/ftdetect for the languages that used to have a
" plugin each. Three packs are switched off deliberately:
"   go          -- polyglot ships Go *syntax only*; vim-go is kept for its 55
"                  commands (:GoDef, :GoImports, :GoTest, ...)
"   autoindent  -- polyglot bundles an older vim-sleuth without .editorconfig
"                  support; the standalone vim-sleuth is kept instead
"   sensible    -- option ownership stays in this file
" This must be set before polyglot loads.
let g:polyglot_disabled = ['go', 'autoindent', 'sensible']

" pathogen - the runtime for Vim plugins
execute pathogen#infect()
" NOTE: help tags are generated by update_bundles.sh, not here -- running
" :Helptags on every launch re-tagged all bundles for ~11ms of pure startup.

""" Shortcut settings

" set space as leader key
let mapleader=" "

"" Leader prefixed bindings

" double leader to switch between current and last edit file
nnoremap <leader><leader> <c-^>

" open vimo key binding help
nnoremap <leader>h :help vimo<CR>

" open new splits
nnoremap <leader>s :vsp<CR>
nnoremap <leader>S :sp<CR>

" write file
nnoremap <leader>w :w<CR>
nnoremap <leader>W :w!<CR>

" quit
nnoremap <leader>q :q<CR>
nnoremap <leader>Q :q!<CR>

" paste
" nnoremap <leader>p :set paste<CR>
" nnoremap <leader>P :set nopaste<CR>

" tree
function! ToggleNERDTreeFind()
  if g:NERDTree.IsOpen()
    NERDTreeClose
  else
    NERDTreeFind
  endif
endfunction

nnoremap <silent> <leader>t :call ToggleNERDTreeFind()<CR>
nnoremap <silent> <leader>T :NERDTreeToggle<CR>

" zoom
function! s:ZoomToggle() abort
  if exists('t:zoomed') && t:zoomed
    execute t:zoom_winrestcmd
    let t:zoomed = 0
  else
    let t:zoom_winrestcmd = winrestcmd()
    resize
    vertical resize
    let t:zoomed = 1
  endif
endfunction
command! ZoomToggle call s:ZoomToggle()
nnoremap <silent> <leader>o :ZoomToggle<CR>

" browse files/buffers (fzf)
nnoremap <leader>b :Files<CR>
nnoremap <leader>B :Buffers<CR>
nnoremap <leader>l :BLines<CR>

" search text patterns (quickfix; see the :Grep command below)
nnoremap <leader>a :Grep<SPACE>
" -w matches whole words, so `id` does not also hit `width`/`uuid`/`valid`
nnoremap <leader>k :Grep -w <C-R><C-W><CR>

" undo history
nnoremap <silent> <leader>u :UndotreeToggle<CR>

" run tests
nnoremap <silent> <leader>n :TestNearest<CR>
nnoremap <silent> <leader>N :TestFile<CR>

" show the leader-key popup on demand. Mapping <leader> itself would
" intercept every leader press; this leaves the other bindings feeling native.
nnoremap <silent> <leader>? :WhichKey '<Space>'<CR>

" rebuild ctags
nnoremap <leader>r :!ctags --recurse=yes --exclude=.git --exclude=.next --exclude=node_modules --exclude=_book .<CR>

" moving between windows
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

if executable('rg')
  " Use ripgrep over grep. --hidden keeps dotfiles (.env, .github/) searchable;
  " the glob still excludes VCS internals, and .gitignore is respected, so
  " node_modules and build output stay out of the quickfix list.
  set grepprg=rg\ --vimgrep\ --smart-case\ --hidden\ --glob\ '!.git/'
  set grepformat=%f:%l:%c:%m

  " Quickfix-based project search. Named :Grep rather than :Rg because
  " fzf.vim defines its own :Rg in plugin/fzf.vim, and plugin files load
  " after this file -- an :Rg here would be silently clobbered at startup.
  " Defined inside this guard: without rg it would drive the stock
  " non-recursive `grep -n`.
  command! -nargs=+ -complete=file -bar Grep silent! grep! <args> | cwindow | redraw!
  nnoremap \ :Grep<SPACE>
endif

""" EasyMotion settings

" configs
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1

" shortcuts
map <leader>f <Plug>(easymotion-bd-w)
map  / <Plug>(easymotion-sn)
omap  / <Plug>(easymotion-tn)

""" EasyAlign settings

" shortcuts
vmap <Enter> <Plug>(EasyAlign)
" Align GitHub-flavored Markdown tables. Grouped so re-sourcing this file
" replaces the autocmd instead of stacking another copy, and buffer-local so
" the mapping does not leak into every other filetype.
augroup vimo_easyalign
  autocmd!
  autocmd FileType markdown
        \ vmap <buffer> <Leader><Bslash> :EasyAlign*<Bar><Enter>
augroup END

""" Color settings
let g:gruvbox_material_background = 'medium'
let g:gruvbox_material_foreground = 'material'
let g:gruvbox_material_better_performance = 1
colorscheme gruvbox-material

""" ALE settings (linting, fixing, LSP)

" ALE replaces vim-prettier and covers linting and LSP in a single plugin.
"
" Prettier precedence note: the old g:prettier#config#* block set
" 'config_precedence = prefer-file', i.e. a project's own prettier config
" wins. ALE runs the prettier binary, which reads .prettierrc itself, so that
" intent is preserved and no CLI overrides are passed here. Every other value
" in that block matched a prettier default except trailing_comma = 'none'; in
" a project with *no* prettier config you now get prettier's own default
" instead. To restore it globally:
"   let g:ale_javascript_prettier_options = '--trailing-comma none'

" Linters are left to ALE's auto-detection: it only runs the ones it finds on
" PATH, so an explicit list would just go stale.
let g:ale_fixers = {
      \ '*': ['remove_trailing_lines', 'trim_whitespace'],
      \ 'javascript': ['prettier'],
      \ 'javascriptreact': ['prettier'],
      \ 'typescript': ['prettier'],
      \ 'typescriptreact': ['prettier'],
      \ 'json': ['prettier'],
      \ 'css': ['prettier'],
      \ 'scss': ['prettier'],
      \ 'less': ['prettier'],
      \ 'html': ['prettier'],
      \ 'yaml': ['prettier'],
      \ 'markdown': ['prettier'],
      \ 'graphql': ['prettier'],
      \ 'go': ['gofmt'],
      \ 'rust': ['rustfmt'],
      \ 'terraform': ['terraform'],
      \ }

" Fix on demand, not on save: a formatter rewriting the buffer under you is
" worse than pressing <leader>p.
let g:ale_fix_on_save = 0

" Lint on save and on leaving insert rather than on every keystroke.
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_enter = 1

" ALE shares the sign column with gitgutter; 'signcolumn=yes' stops jitter.
let g:ale_sign_error = 'E'
let g:ale_sign_warning = 'W'
let g:ale_echo_msg_format = '[%linter%] %s'

" LSP-backed completion, reached through SuperTab (see below).
let g:ale_completion_enabled = 1

" shortcuts. [w/]w are free: vim-unimpaired claims neither, and gitgutter
" owns [c/]c for hunks.
nnoremap <leader>p :ALEFix<CR>
nnoremap <leader>d :ALEDetail<CR>
nnoremap <leader>g :ALEGoToDefinition<CR>
nnoremap <silent> [w :ALEPreviousWrap<CR>
nnoremap <silent> ]w :ALENextWrap<CR>

""" SuperTab settings

" 'context' picks the completion type from what precedes the cursor, which is
" what makes ALE's omnifunc (LSP) completion reachable from <Tab> instead of
" always falling back to plain keyword completion.
let g:SuperTabDefaultCompletionType = 'context'
let g:SuperTabContextDefaultCompletionType = '<c-n>'

""" Gutentags settings

" Keep generated tags files out of the projects themselves.
let g:gutentags_cache_dir = expand('~/.cache/gutentags')
if !isdirectory(g:gutentags_cache_dir)
  call mkdir(g:gutentags_cache_dir, 'p', 0700)
endif
let g:gutentags_ctags_exclude = ['.git', '.next', 'node_modules', '_book']

" Gutentags shells out to `ctags -R`, which the BSD ctags shipped with macOS
" and the Xcode command line tools does not support -- it rejects both -R and
" --recurse. Load it only when a usable ctags is on PATH, otherwise every save
" would raise an error. install_vim.sh / install_neovim.sh report on this and
" say what to install; <leader>r has the same requirement.
"
" The check is deliberately subprocess-free. Asking `ctags --version` would be
" authoritative, but system() spawns a shell: measured here at ~470ms added to
" every single startup, against a ~60ms baseline. Path inspection is free.
let s:ctags = exepath('ctags')
let g:gutentags_dont_load = 1
if !empty(s:ctags)
  if has('mac') || has('macunix')
    " macOS keeps its BSD ctags in /usr/bin, and the Xcode command line tools
    " ship theirs under /Library/Developer. Anything else on PATH -- notably
    " Homebrew's universal-ctags -- is the real thing.
    if s:ctags !~# '^\%(/usr/bin\|/Library/Developer\)/'
      let g:gutentags_dont_load = 0
    endif
  else
    " Elsewhere /usr/bin/ctags is usually universal-ctags already.
    let g:gutentags_dont_load = 0
  endif
endif

""" Undotree settings

let g:undotree_SetFocusWhenToggle = 1
let g:undotree_WindowLayout = 2

""" matchup settings

" show an off-screen opening delimiter in a popup instead of the status line
let g:matchup_matchparen_offscreen = {'method': 'popup'}
" defer highlighting so large files stay responsive
let g:matchup_matchparen_deferred = 1

""" fzf settings

" fzf.vim also provides :Rg and :RG (interactive, with a preview window).
" The quickfix-based project search is :Grep -- see the ripgrep block above.
let g:fzf_layout = { 'down': '40%' }

""" vim-test settings

let g:test#strategy = 'basic'
