" 'nocompatible' comes first: if it ever flips (e.g. `vim -u this-file`) it
" resets other options. Implied when Vim finds ~/.vimrc; a no-op in Neovim.
set nocompatible

""" Global settings

" turn on syntax highlight
syntax on

" turn on true color
set termguicolors
if !has('nvim')
  " terminal Vim only emits truecolor escapes if these are set
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

" highlight search
set hlsearch

" disable mouse reporting
set mouse=

" filetype based indentation
filetype plugin indent on
" fallback to autoindent
" which does nothing more than copy the indentation from the previous line
" when starting a new line
set autoindent

" expand tab using space characters, each tab equals to 2 spaces
set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2

" a special column at the 80 character warns lines that are too long
set colorcolumn=80

" encoding settings
set encoding=utf-8

" more natural split opening
set splitbelow
set splitright

" no swapfile: this config began life in a container where the host user was
" mapped in, so swap writes to mounted directories hit permission errors.
" Kept since 'undofile' plus git cover the recovery case.
set noswapfile

" persist command/search history, marks and registers across sessions.
" ('viminfo' is the Vim name; Neovim accepts it as an alias for 'shada'.)
"   '100  marks for the last 100 files   <50  max 50 lines per register
"   s10   skip registers above 10KB      h    don't restore hlsearch on start
set viminfo='100,<50,s10,h

" read a project-local vimrc (Vim: ./.vimrc -- nvim 0.9+: ./.nvim.lua,
" ./.nvimrc or ./.exrc, behind a trust prompt). 'secure' restricts what such
" a file may do, which is what protects Vim, where there is no trust prompt.
set exrc
set secure

" disable safe write
set backupcopy=yes

" automatically read file changes
set autoread

" do not generate files ending with ~
" set nowritebackup

" Display extra whitespace
" set list listchars=tab:,trail:·,nbsp:·

""" Improved defaults
"
" NOTE: many settings below (hidden, incsearch, wildmenu, laststatus=2,
" autoindent, encoding, autoread, hlsearch, and syntax/filetype above) are
" already Neovim defaults but are NOT Vim defaults -- do not drop them as
" redundant, they are load-bearing under Vim.

" line numbers (relative + absolute current line)
set number
set relativenumber

" smart search: case-insensitive unless uppercase is typed
set ignorecase
set smartcase
set incsearch

" allow switching buffers without saving
set hidden

" command-line completion
set wildmenu
set wildmode=longest:full,full

" keep context lines visible when scrolling
set scrolloff=8
set sidescrolloff=8

" highlight current line
set cursorline

" always show the sign column (prevents gitgutter jitter)
set signcolumn=yes

" faster gitgutter + CursorHold events (default 4000ms is too slow)
set updatetime=250

" live preview of :s/// as you type
if exists('&inccommand')
  set inccommand=split
endif

" redundant with airline
set noshowmode

" persistent undo across sessions, kept outside this repo
set undofile
if has('nvim')
  let s:undodir = expand('~/.config/nvim/undodir')
else
  let s:undodir = expand('~/.vim/undodir')
endif
if !isdirectory(s:undodir)
  call mkdir(s:undodir, 'p', 0700)
endif
let &undodir = s:undodir

" system clipboard integration.
" nvim routes the '+' register to the OS clipboard. Vim on macOS is built
" without X11, so '+' never reaches the pasteboard and 'unnamedplus' silently
" does nothing there -- '*' is the register that works.
if has('nvim')
  set clipboard=unnamedplus
elseif has('clipboard')
  set clipboard=unnamed
endif

" always show status line
set laststatus=2

" backspace over autoindent, line breaks and start-of-insert (Vim is limited
" here by default; already the Neovim default)
set backspace=indent,eol,start

" recognise terminal key codes without hanging on a bare <Esc>
set ttimeout
set ttimeoutlen=100

""" Package manager settings

" pathogen - the runtime for Vim plugins
execute pathogen#infect()
" NOTE: help tags are generated by update_bundles.sh, not here -- running
" :Helptags on every launch re-tagged all bundles for ~11ms of pure startup.

""" Shortcut settings

" set space as leader key
let mapleader=" "

"" Leader prefixed bindings

" double leader to switch between current and last edit file
nnoremap <leader><leader> <c-^>

" open vimo key binding help
nnoremap <leader>h :help vimo<CR>

" open new splits
nnoremap <leader>s :vsp<CR>
nnoremap <leader>S :sp<CR>

" write file
nnoremap <leader>w :w<CR>
nnoremap <leader>W :w!<CR>

" quit
nnoremap <leader>q :q<CR>
nnoremap <leader>Q :q!<CR>

" paste
" nnoremap <leader>p :set paste<CR>
" nnoremap <leader>P :set nopaste<CR>

" tree
function! ToggleNERDTreeFind()
  if g:NERDTree.IsOpen()
    NERDTreeClose
  else
    NERDTreeFind
  endif
endfunction

nnoremap <silent> <leader>t :call ToggleNERDTreeFind()<CR>
nnoremap <silent> <leader>T :NERDTreeToggle<CR>

" zoom
function! s:ZoomToggle() abort
  if exists('t:zoomed') && t:zoomed
    execute t:zoom_winrestcmd
    let t:zoomed = 0
  else
    let t:zoom_winrestcmd = winrestcmd()
    resize
    vertical resize
    let t:zoomed = 1
  endif
endfunction
command! ZoomToggle call s:ZoomToggle()
nnoremap <silent> <leader>o :ZoomToggle<CR>

" browse files/buffers
nnoremap <leader>b :CtrlPMixed<CR>

" search text patterns
nnoremap <leader>a :Rg<SPACE>
" -w matches whole words, so `id` does not also hit `width`/`uuid`/`valid`
nnoremap <leader>k :Rg -w <C-R><C-W><CR>

" rebuild ctags
nnoremap <leader>r :!ctags --recurse=yes --exclude=.git --exclude=.next --exclude=node_modules --exclude=_book .<CR>

" moving between windows
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

if executable('rg')
  " Use ripgrep over grep. --hidden keeps dotfiles (.env, .github/) searchable;
  " the glob still excludes VCS internals, and .gitignore is respected, so
  " node_modules and build output stay out of the quickfix list.
  set grepprg=rg\ --vimgrep\ --smart-case\ --hidden\ --glob\ '!.git/'
  set grepformat=%f:%l:%c:%m

  " Use rg in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'rg --files --hidden --glob "!.git" %s'

  " rg is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0

  " search command using grepprg. Defined here rather than unconditionally:
  " without rg it would silently drive the stock non-recursive `grep -n`.
  command! -nargs=+ -complete=file -bar Rg silent! grep! <args> | cwindow | redraw!
  nnoremap \ :Rg<SPACE>
endif

""" EasyMotion settings

" configs
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1

" shortcuts
map <leader>f <Plug>(easymotion-bd-w)
map  / <Plug>(easymotion-sn)
omap  / <Plug>(easymotion-tn)

""" EasyAlign settings

" shortcuts
vmap <Enter> <Plug>(EasyAlign)
" Align GitHub-flavored Markdown tables. Grouped so re-sourcing this file
" replaces the autocmd instead of stacking another copy, and buffer-local so
" the mapping does not leak into every other filetype.
augroup vimo_easyalign
  autocmd!
  autocmd FileType markdown
        \ vmap <buffer> <Leader><Bslash> :EasyAlign*<Bar><Enter>
augroup END

""" Color settings
let g:gruvbox_material_background = 'medium'
let g:gruvbox_material_foreground = 'material'
let g:gruvbox_material_better_performance = 1
colorscheme gruvbox-material

""" Prettier settings

" max line length that prettier will wrap on
" Prettier default: 80
let g:prettier#config#print_width = 80

" number of spaces per indentation level
" Prettier default: 2
let g:prettier#config#tab_width = 2

" use tabs over spaces
" Prettier default: false
let g:prettier#config#use_tabs = 'false'

" print semicolons
" Prettier default: true
let g:prettier#config#semi = 'true'

" single quotes over double quotes
" Prettier default: false
let g:prettier#config#single_quote = 'false'

" print spaces between brackets
" Prettier default: true
let g:prettier#config#bracket_spacing = 'true'

" put > on the last line instead of new line
" Prettier default: false
let g:prettier#config#jsx_bracket_same_line = 'false'

" none|es5|all
" Prettier default: none
let g:prettier#config#trailing_comma = 'none'

" flow|babylon|typescript|css|less|scss|json|graphql|markdown
" Prettier default: babylon
"let g:prettier#config#parser = 'babylon'

" cli-override|file-override|prefer-file
let g:prettier#config#config_precedence = 'prefer-file'

" always|never|preserve
let g:prettier#config#prose_wrap = 'preserve'
